debug revert

diff --git a/.github/workflows/CargoHub.yml b/.github/workflows/CargoHub.yml
--- a/.github/workflows/CargoHub.yml
+++ b/.github/workflows/CargoHub.yml
@@ -5,7 +5,7 @@ on:
 
 jobs:
   build:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
@@ -14,6 +14,17 @@ jobs:
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '8.0.x'
+    
+    - name: Set up Python 3.12
+      uses: actions/setup-python@v5
+      with:
+        python-version: "3.12"
+        cache: 'pip'
+    
+    - name: Install Python Dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pytest requests
 
     - name: Restore Dependencies
       run: dotnet restore
@@ -25,31 +36,35 @@ jobs:
 
   test:
     needs: build
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
 
-    - name: Set up Python 3.12
-      uses: actions/setup-python@v5
-      with:
-        python-version: "3.12"
-        cache: 'pip'
-
-    - name: Install Python Dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pytest requests
-
-    - name: Setup .NET SDK
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: '8.0.x'
-
     - name: Start CargoHub Web Application
       run: |
-        dotnet run --project ./CargoHubV2/CargohubV2.csproj --urls http://0.0.0.0:5000 &
-        sleep 10
+        nohup dotnet run > output.log &
+      working-directory: CargoHubV2
+    
+    - name: Wait for ASP.NET application to start (health check)
+      run: |
+        echo "Waiting for ASP.NET application to start..."
+
+        for i in {1..120}; do  # Retry every 5 seconds, up to 20 times (10 minutes total)
+          if curl -s http://localhost:5000/api/ | grep "Healthy"; then
+            echo "ASP.NET application is healthyt!"
+            break
+          fi
+          echo "Still waiting for ASP.NET application... (Attempt $i)"
+          sleep 5
+        done
+
+        if ! curl -s http://localhost:5000/api/ | grep "Healthy"; then
+          echo "Error: ASP.NET application is not healthy!"
+          cat output.log
+          exit 1
+        fi
 
     - name: Run Integration Tests
-      run: pytest ./CargoHubTest/IntegrationTests
+      run: pytest
+      working-directory: CargoHubTest 
